export const container: string;
export const section: string;
export const text: string;
export const centerText: string;
export const alignCenter: string;
export const code: string;
export const title: string;
export const subtitle: string;
export const p: string;
